db.movies.insertOne({
  title: "The Favourite",
  genres: ["Drama", "History"],
  runtime: 121,
  rated: "R",
  year: 2018,
  directors: ["Yorgos Lanthimos"],
  cast: ["Olivia Colman", "Emma Stone", "Rachel Weisz"],
  type: "movie",
});

db.movies.insertMany([
  {
    title: "Jurassic World: Fallen Kingdom",
    genres: ["Action", "Sci-Fi"],
    runtime: 130,
    rated: "PG-13",
    year: 2018,
    directors: ["J. A. Bayona"],
    cast: ["Chris Pratt", "Bryce Dallas Howard", "Rafe Spall"],
    type: "movie",
  },
  {
    title: "Tag",
    genres: ["Comedy", "Action"],
    runtime: 105,
    rated: "R",
    year: 2018,
    directors: ["Jeff Tomsic"],
    cast: ["Annabelle Wallis", "Jeremy Renner", "Jon Hamm"],
    type: "movie",
  },
]);

//insert new movie
db.movies.insertMany([
  {
    title: "Inception",
    genres: ["Action", "Sci-Fi", "Thriller"],
    runtime: 148,
    rated: "PG-13",
    year: 2010,
    directors: ["Christopher Nolan"],
    cast: ["Leonardo DiCaprio", "Joseph Gordon-Levitt", "Ellen Page"],
    type: "movie",
  },

  {
    title: "The Matrix",
    genres: ["Action", "Sci-Fi"],
    runtime: 136,
    rated: "R",
    year: 1999,
    directors: ["The Wachowskis"],
    cast: ["Keanu Reeves", "Laurence Fishburne", "Carrie-Anne Moss"],
    type: "movie",
  },

  {
    title: "Avatar",
    genres: ["Action", "Adventure", "Sci-Fi"],
    runtime: 162,
    rated: "PG-13",
    year: 2009,
    directors: ["James Cameron"],
    cast: ["Sam Worthington", "Zoe Saldana", "Sigourney Weaver"],
    type: "movie",
  },

  {
    title: "The Dark Knight",
    genres: ["Action", "Crime", "Drama"],
    runtime: 152,
    rated: "PG-13",
    year: 2008,
    directors: ["Christopher Nolan"],
    cast: ["Christian Bale", "Heath Ledger", "Aaron Eckhart"],
    type: "movie",
  },

  {
    title: "Guardians of the Galaxy",
    genres: ["Action", "Adventure", "Sci-Fi"],
    runtime: 121,
    rated: "PG-13",
    year: 2014,
    directors: ["James Gunn"],
    cast: ["Chris Pratt", "Zoe Saldana", "Dave Bautista"],
    type: "movie",
  },
]);

//insert 50 new movie
db.movies.insertMany([
  {
    title: "Interstellar",
    genres: ["Adventure", "Drama", "Sci-Fi"],
    runtime: 169,
    rated: "PG-13",
    year: 2014,
    directors: ["Christopher Nolan"],
    cast: ["Matthew McConaughey", "Anne Hathaway", "Jessica Chastain"],
    type: "movie",
  },
  {
    title: "Mad Max: Fury Road",
    genres: ["Action", "Adventure", "Sci-Fi"],
    runtime: 120,
    rated: "R",
    year: 2015,
    directors: ["George Miller"],
    cast: ["Tom Hardy", "Charlize Theron", "Nicholas Hoult"],
    type: "movie",
  },
  {
    title: "The Avengers",
    genres: ["Action", "Adventure", "Sci-Fi"],
    runtime: 143,
    rated: "PG-13",
    year: 2012,
    directors: ["Joss Whedon"],
    cast: ["Robert Downey Jr.", "Chris Evans", "Scarlett Johansson"],
    type: "movie",
  },
  {
    title: "Titanic",
    genres: ["Drama", "Romance"],
    runtime: 195,
    rated: "PG-13",
    year: 1997,
    directors: ["James Cameron"],
    cast: ["Leonardo DiCaprio", "Kate Winslet", "Billy Zane"],
    type: "movie",
  },
  {
    title: "Jurassic Park",
    genres: ["Action", "Adventure", "Sci-Fi"],
    runtime: 127,
    rated: "PG-13",
    year: 1993,
    directors: ["Steven Spielberg"],
    cast: ["Sam Neill", "Laura Dern", "Jeff Goldblum"],
    type: "movie",
  },
  {
    title: "Star Wars: Episode IV - A New Hope",
    genres: ["Action", "Adventure", "Fantasy"],
    runtime: 121,
    rated: "PG",
    year: 1977,
    directors: ["George Lucas"],
    cast: ["Mark Hamill", "Harrison Ford", "Carrie Fisher"],
    type: "movie",
  },
  {
    title: "The Lord of the Rings: The Fellowship of the Ring",
    genres: ["Action", "Adventure", "Drama"],
    runtime: 178,
    rated: "PG-13",
    year: 2001,
    directors: ["Peter Jackson"],
    cast: ["Elijah Wood", "Ian McKellen", "Orlando Bloom"],
    type: "movie",
  },
  {
    title: "Gladiator",
    genres: ["Action", "Adventure", "Drama"],
    runtime: 155,
    rated: "R",
    year: 2000,
    directors: ["Ridley Scott"],
    cast: ["Russell Crowe", "Joaquin Phoenix", "Connie Nielsen"],
    type: "movie",
  },
  {
    title: "The Shawshank Redemption",
    genres: ["Drama"],
    runtime: 142,
    rated: "R",
    year: 1994,
    directors: ["Frank Darabont"],
    cast: ["Tim Robbins", "Morgan Freeman", "Bob Gunton"],
    type: "movie",
  },
  {
    title: "Forrest Gump",
    genres: ["Drama", "Romance"],
    runtime: 142,
    rated: "PG-13",
    year: 1994,
    directors: ["Robert Zemeckis"],
    cast: ["Tom Hanks", "Robin Wright", "Gary Sinise"],
    type: "movie",
  },
  {
    title: "The Lion King",
    genres: ["Animation", "Adventure", "Drama"],
    runtime: 88,
    rated: "G",
    year: 1994,
    directors: ["Roger Allers", "Rob Minkoff"],
    cast: ["Matthew Broderick", "Jeremy Irons", "James Earl Jones"],
    type: "movie",
  },
  {
    title: "The Silence of the Lambs",
    genres: ["Crime", "Drama", "Thriller"],
    runtime: 118,
    rated: "R",
    year: 1991,
    directors: ["Jonathan Demme"],
    cast: ["Jodie Foster", "Anthony Hopkins", "Lawrence A. Bonney"],
    type: "movie",
  },
  {
    title: "Pulp Fiction",
    genres: ["Crime", "Drama"],
    runtime: 154,
    rated: "R",
    year: 1994,
    directors: ["Quentin Tarantino"],
    cast: ["John Travolta", "Uma Thurman", "Samuel L. Jackson"],
    type: "movie",
  },
  {
    title: "The Godfather",
    genres: ["Crime", "Drama"],
    runtime: 175,
    rated: "R",
    year: 1972,
    directors: ["Francis Ford Coppola"],
    cast: ["Marlon Brando", "Al Pacino", "James Caan"],
    type: "movie",
  },
  {
    title: "Fight Club",
    genres: ["Drama"],
    runtime: 139,
    rated: "R",
    year: 1999,
    directors: ["David Fincher"],
    cast: ["Brad Pitt", "Edward Norton", "Meat Loaf"],
    type: "movie",
  },
  {
    title: "The Social Network",
    genres: ["Biography", "Drama"],
    runtime: 120,
    rated: "PG-13",
    year: 2010,
    directors: ["David Fincher"],
    cast: ["Jesse Eisenberg", "Andrew Garfield", "Justin Timberlake"],
    type: "movie",
  },
  {
    title: "The Wolf of Wall Street",
    genres: ["Biography", "Comedy", "Crime"],
    runtime: 180,
    rated: "R",
    year: 2013,
    directors: ["Martin Scorsese"],
    cast: ["Leonardo DiCaprio", "Jonah Hill", "Margot Robbie"],
    type: "movie",
  },
  {
    title: "Django Unchained",
    genres: ["Drama", "Western"],
    runtime: 165,
    rated: "R",
    year: 2012,
    directors: ["Quentin Tarantino"],
    cast: ["Jamie Foxx", "Christoph Waltz", "Leonardo DiCaprio"],
    type: "movie",
  },
  {
    title: "Whiplash",
    genres: ["Drama", "Music"],
    runtime: 106,
    rated: "R",
    year: 2014,
    directors: ["Damien Chazelle"],
    cast: ["Miles Teller", "J.K. Simmons", "Melissa Benoist"],
    type: "movie",
  },
  {
    title: "The Grand Budapest Hotel",
    genres: ["Adventure", "Comedy", "Crime"],
    runtime: 99,
    rated: "R",
    year: 2014,
    directors: ["Wes Anderson"],
    cast: ["Ralph Fiennes", "F. Murray Abraham", "Mathieu Amalric"],
    type: "movie",
  },
  {
    title: "The Great Gatsby",
    genres: ["Drama", "Romance"],
    runtime: 143,
    rated: "PG-13",
    year: 2013,
    directors: ["Baz Luhrmann"],
    cast: ["Leonardo DiCaprio", "Carey Mulligan", "Joel Edgerton"],
    type: "movie",
  },
  {
    title: "Black Panther",
    genres: ["Action", "Adventure", "Sci-Fi"],
    runtime: 134,
    rated: "PG-13",
    year: 2018,
    directors: ["Ryan Coogler"],
    cast: ["Chadwick Boseman", "Michael B. Jordan", "Lupita Nyong'o"],
    type: "movie",
  },
  {
    title: "Iron Man",
    genres: ["Action", "Adventure", "Sci-Fi"],
    runtime: 126,
    rated: "PG-13",
    year: 2008,
    directors: ["Jon Favreau"],
    cast: ["Robert Downey Jr.", "Gwyneth Paltrow", "Terrence Howard"],
    type: "movie",
  },
  {
    title: "Spider-Man: Homecoming",
    genres: ["Action", "Adventure", "Sci-Fi"],
    runtime: 133,
    rated: "PG-13",
    year: 2017,
    directors: ["Jon Watts"],
    cast: ["Tom Holland", "Michael Keaton", "Robert Downey Jr."],
    type: "movie",
  },
  {
    title: "Doctor Strange",
    genres: ["Action", "Adventure", "Fantasy"],
    runtime: 115,
    rated: "PG-13",
    year: 2016,
    directors: ["Scott Derrickson"],
    cast: ["Benedict Cumberbatch", "Chiwetel Ejiofor", "Rachel McAdams"],
    type: "movie",
  },
  {
    title: "Deadpool",
    genres: ["Action", "Adventure", "Comedy"],
    runtime: 108,
    rated: "R",
    year: 2016,
    directors: ["Tim Miller"],
    cast: ["Ryan Reynolds", "Morena Baccarin", "T.J. Miller"],
    type: "movie",
  },
  {
    title: "The Revenant",
    genres: ["Action", "Adventure", "Drama"],
    runtime: 156,
    rated: "R",
    year: 2015,
    directors: ["Alejandro G. Iñárritu"],
    cast: ["Leonardo DiCaprio", "Tom Hardy", "Will Poulter"],
    type: "movie",
  },
  {
    title: "The Imitation Game",
    genres: ["Biography", "Drama", "Thriller"],
    runtime: 113,
    rated: "PG-13",
    year: 2014,
    directors: ["Morten Tyldum"],
    cast: ["Benedict Cumberbatch", "Keira Knightley", "Matthew Goode"],
    type: "movie",
  },
  {
    title: "The Martian",
    genres: ["Adventure", "Drama", "Sci-Fi"],
    runtime: 144,
    rated: "PG-13",
    year: 2015,
    directors: ["Ridley Scott"],
    cast: ["Matt Damon", "Jessica Chastain", "Kristen Wiig"],
    type: "movie",
  },
  {
    title: "Blade Runner 2049",
    genres: ["Action", "Drama", "Sci-Fi"],
    runtime: 164,
    rated: "R",
    year: 2017,
    directors: ["Denis Villeneuve"],
    cast: ["Ryan Gosling", "Harrison Ford", "Ana de Armas"],
    type: "movie",
  },
  {
    title: "Parasite",
    genres: ["Comedy", "Drama", "Thriller"],
    runtime: 132,
    rated: "R",
    year: 2019,
    directors: ["Bong Joon Ho"],
    cast: ["Song Kang-ho", "Lee Sun-kyun", "Cho Yeo-jeong"],
    type: "movie",
  },
  {
    title: "Jojo Rabbit",
    genres: ["Comedy", "Drama", "War"],
    runtime: 108,
    rated: "PG-13",
    year: 2019,
    directors: ["Taika Waititi"],
    cast: ["Roman Griffin Davis", "Thomasin McKenzie", "Scarlett Johansson"],
    type: "movie",
  },
  {
    title: "Once Upon a Time in Hollywood",
    genres: ["Comedy", "Drama"],
    runtime: 161,
    rated: "R",
    year: 2019,
    directors: ["Quentin Tarantino"],
    cast: ["Leonardo DiCaprio", "Brad Pitt", "Margot Robbie"],
    type: "movie",
  },
  {
    title: "Joker",
    genres: ["Crime", "Drama", "Thriller"],
    runtime: 122,
    rated: "R",
    year: 2019,
    directors: ["Todd Phillips"],
    cast: ["Joaquin Phoenix", "Robert De Niro", "Zazie Beetz"],
    type: "movie",
  },
  {
    title: "1917",
    genres: ["Action", "Drama", "War"],
    runtime: 119,
    rated: "R",
    year: 2019,
    directors: ["Sam Mendes"],
    cast: ["Dean-Charles Chapman", "George MacKay", "Daniel Mays"],
    type: "movie",
  },
  {
    title: "Marriage Story",
    genres: ["Drama", "Romance"],
    runtime: 137,
    rated: "R",
    year: 2019,
    directors: ["Noah Baumbach"],
    cast: ["Adam Driver", "Scarlett Johansson", "Julia Greer"],
    type: "movie",
  },
  {
    title: "Ford v Ferrari",
    genres: ["Action", "Biography", "Drama"],
    runtime: 152,
    rated: "PG-13",
    year: 2019,
    directors: ["James Mangold"],
    cast: ["Matt Damon", "Christian Bale", "Jon Bernthal"],
    type: "movie",
  },
  {
    title: "A Quiet Place",
    genres: ["Drama", "Horror", "Sci-Fi"],
    runtime: 90,
    rated: "PG-13",
    year: 2018,
    directors: ["John Krasinski"],
    cast: ["Emily Blunt", "John Krasinski", "Millicent Simmonds"],
    type: "movie",
  },
  {
    title: "Hereditary",
    genres: ["Drama", "Horror", "Mystery"],
    runtime: 127,
    rated: "R",
    year: 2018,
    directors: ["Ari Aster"],
    cast: ["Toni Collette", "Milly Shapiro", "Gabriel Byrne"],
    type: "movie",
  },
  {
    title: "Get Out",
    genres: ["Horror", "Mystery", "Thriller"],
    runtime: 104,
    rated: "R",
    year: 2017,
    directors: ["Jordan Peele"],
    cast: ["Daniel Kaluuya", "Allison Williams", "Bradley Whitford"],
    type: "movie",
  },
  {
    title: "Us",
    genres: ["Horror", "Mystery", "Thriller"],
    runtime: 116,
    rated: "R",
    year: 2019,
    directors: ["Jordan Peele"],
    cast: ["Lupita Nyong'o", "Winston Duke", "Elisabeth Moss"],
    type: "movie",
  },
  {
    title: "Midsommar",
    genres: ["Drama", "Horror", "Mystery"],
    runtime: 148,
    rated: "R",
    year: 2019,
    directors: ["Ari Aster"],
    cast: ["Florence Pugh", "Jack Reynor", "Vilhelm Blomgren"],
    type: "movie",
  },
  {
    title: "The Lighthouse",
    genres: ["Drama", "Fantasy", "Horror"],
    runtime: 109,
    rated: "R",
    year: 2019,
    directors: ["Robert Eggers"],
    cast: ["Robert Pattinson", "Willem Dafoe", "Valeriia Karaman"],
    type: "movie",
  },
  {
    title: "The Irishman",
    genres: ["Biography", "Crime", "Drama"],
    runtime: 209,
    rated: "R",
    year: 2019,
    directors: ["Martin Scorsese"],
    cast: ["Robert De Niro", "Al Pacino", "Joe Pesci"],
    type: "movie",
  },
  {
    title: "Avengers: Endgame",
    genres: ["Action", "Adventure", "Drama"],
    runtime: 181,
    rated: "PG-13",
    year: 2019,
    directors: ["Anthony Russo", "Joe Russo"],
    cast: ["Robert Downey Jr.", "Chris Evans", "Mark Ruffalo"],
    type: "movie",
  },
  {
    title: "Shutter Island",
    genres: ["Mystery", "Thriller"],
    runtime: 138,
    rated: "R",
    year: 2010,
    directors: ["Martin Scorsese"],
    cast: ["Leonardo DiCaprio", "Emily Mortimer", "Mark Ruffalo"],
    type: "movie",
  },
  

]);

   
